emirathes/Models/Passengers.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace emirathes.Models
{
    public class Passengers
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Description { get; set; }
        [Required]
        public string Name { get; set; }

        [Required]
        public double Percentage { get; set; }
        public bool IsPassenger { get; set; } = true;


    }
}

emirathes/Areas/Admin/Controllers/PassengersController.cs
using emirathes.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;


namespace emirathes.Areas.Admin.Controllers
{
    [Area("Admin")]
    //[Authorize(Roles = "Admin")]

    public class PassengersController : Controller
    {


        private readonly AppDbContent appDbContent;

        public PassengersController(AppDbContent _appDbContent)
        {
            appDbContent = _appDbContent;

        }

        public IActionResult Create()
        {
            return View();
        }



        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Create(Passengers passengers)
        {

            if (!ModelState.IsValid)
            {
                return View(passengers);
            }

            appDbContent.Passengers.Add(passengers);
            appDbContent.SaveChanges();
            return RedirectToAction("Index");
        }



        //public IActionResult Delete(int id)
        //{
        //    if (id == 0)
        //    {
        //        return NotFound();
        //    }
        //    var Passengers = appDbContent.Passengers.Find(id);
        //    if (Passengers != null)
        //    {
        //        appDbContent.Passengers.Remove(Passengers);
        //        appDbContent.SaveChanges();
        //    }
        //    return RedirectToAction("Index");

        //}





        [HttpGet]
        public JsonResult Delete(int id)
        {
            if (id == 0)
            {
                return Json(new
                {
                    status = 400
                });
            }

            var passengers = appDbContent.Passengers.Find(id); //axtarib tapiram
            if (passengers != null)
            {
                appDbContent.Passengers.Remove(passengers);
                appDbContent.SaveChanges();
                return Json(new
                {
                    status = 200
                });
            }
            return Json(new
            {
                status = 400
            });

        }



        public IActionResult Edit(int id)
        {
            if (id == 0)
            {
                return View("index");
            }
            var model = appDbContent.Passengers.FirstOrDefault(x => x.Id == id);
            if (model == null)
            {
                return RedirectToAction("Index");

            }
            return View(model);
        }


        [HttpPost]
        public IActionResult Edit(Passengers passengers)
        {
            if (!ModelState.IsValid)
            {
                return View(passengers);
            }
            appDbContent.Passengers.Update(passengers);
            appDbContent.SaveChanges();
            return RedirectToAction(nameof(Index));

        }
        public IActionResult Index()
        {
            return View(appDbContent.Passengers.ToList());
        }
    }
}

emirathes/Areas/Admin/Views/Passengers/Create.cshtml
@model Passengers


<div class="row">
    <div class="col-lg-12">
        <div class="form-box">
            <div class="form-title-wrap">
                <div class="d-flex align-items-center justify-content-between">
                    <div>
                        <h3 class="title">Create</h3>
                    </div>

                </div>
            </div>
            <div class="form-content">
                <div class="table-form table-responsive">


                    <form class="row" style="width: 1000px;" method="post" asp-area="Admin" asp-controller="Passengers" asp-action="Create" enctype="multipart/form-data">

                        @Html.AntiForgeryToken()
                        <div class="col-md-4">
                            <label>
                                Description
                            </label>
                            <input asp-for="Description" type="text" class="form-control" />
                            <span asp-validation-for="Description" class="text-danger"></span>
                        </div>

                        <div class="col-md-4">
                            <label>
                                Name
                            </label>
                            <input asp-for="Name" type="text" class="form-control" />
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>

                        <div class="col-md-4">
                            <label>
                                Percentage
                            </label>
                            <input asp-for="Percentage" type="text" class="form-control" />
                            <span asp-validation-for="Percentage" class="text-danger"></span>
                        </div>

                      


                        <div class="col-md-4">
                            <button type="submit" class="btn btn-danger mt-3 btn-block">Add Database</button>
                        </div>


                    </form>
                </div>
            </div>
        </div><!-- end form-box -->
    </div><!-- end col-lg-12 -->
</div><!-- end row -->

emirathes/Areas/Admin/Views/Passengers/Edit.cshtml
@model Passengers


<div class="row">
    <div class="col-lg-12">
        <div class="form-box">
            <div class="form-title-wrap">
                <div class="d-flex align-items-center justify-content-between">
                    <div>
                        <h3 class="title">Create Feature</h3>
                    </div>

                </div>
            </div>
            <div class="form-content">
                <div class="table-form table-responsive">


                    <form class="row" style="width: 1000px;" method="post" asp-area="Admin" asp-controller="Passengers" asp-action="Edit" enctype="multipart/form-data">

                        @Html.AntiForgeryToken()

                        <div class="col-md-4">
                            <label>
                                Description
                            </label>
                            <br />
                            <input asp-for="Description" type="text" class="form-control" />
                            <span asp-validation-for="Description" class="text-danger"></span>
                        </div>

                        <div class="col-md-4">
                            <label>
                                Feature Name
                            </label>                            
                            <input asp-for="Name" type="text" class="form-control" />
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                        <div class="col-md-4">
                            <label>
                                Percentage
                            </label>
                            <input asp-for="Percentage" type="text" class="form-control" />
                            <span asp-validation-for="Percentage" class="text-danger"></span>
                        </div>


                       

                        <div class="col-md-4">
                            <label>
                                Reviewed
                            </label>
                            <input asp-for="IsPassenger" type="checkbox" class="form-check" />
                        </div>


                        <div class="col-md-4">
                            <button type="submit" class="btn btn-success mt-3 btn-block">Edit</button>
                        </div>

                    </form>
                </div>
            </div>
        </div><!-- end form-box -->
    </div><!-- end col-lg-12 -->
</div><!-- end row -->

emirathes/Areas/Admin/Views/Passengers/Index.cshtml
@model List<Passengers>
@section Styles {
    <link href="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/8.11.8/sweetalert2.min.css" rel="stylesheet" />

}



<!-- Button trigger modal -->
<button type="button" class="btn btn-success mt-2 mb-2 ml-3" data-toggle="modal" data-target="#exampleModal">
    Create
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Create New Rule</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">


                <form id="PassengersCreateForm" class="row" style="width: 500px;" method="post" asp-area="Admin" asp-controller="Passengers" asp-action="Create">

                    @Html.AntiForgeryToken()
                    <div class="col-md-4">
                        <label>
                            Description
                        </label>
                        <input name="Id" type="hidden" class="form-control" />
                        <input name="Description" type="text" class="form-control" />
                    </div>

                    <div class="col-md-4">
                        <label>
                            Name
                        </label>
                        <input name="Name" type="text" class="form-control" />
                    </div>

                    <div class="col-md-4">
                        <label>
                            Percentage
                        </label>
                        <input name="Percentage" type="text" class="form-control" />
                    </div>

                    <div class="col-md-4">
                        <label>
                            Reviewed
                        </label>
                        <input name="IsAvailable" type="checkbox" class="form-check" />
                    </div>


                   

                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                <button form="PassengersCreateForm" type="submit" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>



<div class="form-content">
    <div class="table-form table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Description</th>
                    <th scope="col">Name</th>
                    <th scope="col">Percentage</th>
                    <th scope="col">Operation</th>

                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {



                    <tr>
                        <th>@item.Description</th>
                       
                        <td>@item.Name</td>
                        <td>@item.Percentage</td>                       

                        <td>
                            <a class="btn btn-success" asp-area="Admin" asp-controller="Passengers" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                            <a class="deleteBtn btn btn-danger" asp-area="Admin" asp-controller="Passengers" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                        </td>

                          
                    </tr>
                }

            </tbody>
        </table>
    </div>
</div>
   






@*<div class="modal fade" id="exampleModalEdit" tabindex="-1" aria-labelledby="exampleModalEditLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalEditLabel">Edit Slider</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="SliderEditForm" class="row" method="post" asp-area="admin" asp-controller="slider" asp-action="edit">
                    @Html.AntiForgeryToken()
                    <div class="col-md-12">
                        <input name="Id" type="hidden" class="form-control" />
                        <label>
                            Description
                        </label>
                        <input name="Description" type="text" class="form-control" />
                    </div>
                    <div class="col-md-12">
                        <label>
                            Name
                        </label>
                        <input name="Name" type="text" class="form-control" />
                    </div>
                    <div class="col-md-12">
                        <label>
                            Percentage
                        </label>
                        <input type="text" name="Percentage" class="form-control" />
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button form="SliderEditForm" type="submit" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div> *@








 @section Scripts {
    <script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/8.11.8/sweetalert2.min.js"></script>

    <script>

        $(document).ready(function () {
            $(document).on('click', '.deleteBtn', function (e) {
                e.preventDefault();
                let url = $(this).attr("href");
                let element = this.parentElement.parentElement;

                Swal.fire({
                    title: 'Are you sure you want to do this?',
                    text: "If you delete, you can never get this file back!",
                    type: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Delete',
                    cancelButtonText: 'Back'

                }).then((result) => {
                    if (result.value) {
                        $.ajax({
                            url: url,
                            type: "get",
                            dataType: "json",
                            success: function (response) {
                                console.log(response)
                                if (response.status == 200) {
                                    Swal.fire(
                                        'Deleted!',
                                        '',
                                        'Success'
                                    )
                                    element.outerHTML = '';
                                }
                                else if (response.status == 400) {
                                    //toastr.error(response.message)
                                    Swal.fire({
                                        title: 'Error!',
                                        icon: 'error',
                                        confirmButtonText: 'Cool'
                                    })
                                }
                            }
                        });
                    }
                })
            });
        });


        $(document).ready(() => {
            //Edit(Get)
            $(document).on('click', '.editBtn', (e) => {
                const id = $(e.currentTarget).data('id');

                $.ajax({
                    url: `/Admin/Slider/Edit/${id}`,
                    type: 'GET',
                    success: (response) => {
                        console.log(response)
                        if (response.hasOwnProperty('status') && response.status === 400) {
                            alert('Not Found!');
                        }
                        else {
                            console.log(response);
                            $('#SliderEditForm input[name="Id"]').val(response.id);
                            $('#SliderEditForm input[name="Description"]').val(response.Description);
                            $('#SliderEditForm input[name="Name"]').val(response.Name);
                            $('#SliderEditForm input[name="Percentage"]').val(response.Percentage);
                            $('#SliderEditForm input[name="IsPassengers"]').val(response.IsPassengers);


                        }
                    }
                });
            });


        });



</script>
 }