emirathes/Models/Attribute.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace emirathes.Models
{
    public class Attribute
    {
        [Key]
        public int Id { get; set; }
        public string Title { get; set; }
        public string Baggage { get; set; }
        public string CabinBaggage { get; set; }
       
        //siralama bele olsun
        //CategoryId sonra foreignkey sonra validate never sonra da hemin id yerlesen table
        //Siralama ferqli olanda tanimir ki hansi uchun deyirsiz foreign key

        [ValidateNever]
        public bool IsAvailable { get; set; } = true;

    }
}

emirathes/Areas/Admin/Controllers/AttributesController.cs
using emirathes.Extensions;
using emirathes.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace emirathes.Areas.Admin.Controllers
{
    [Area("Admin")]
    //[Authorize(Roles = "Admin")]

    public class AttributesController : Controller
    {
        private readonly AppDbContent appDbContent;

        public AttributesController(AppDbContent _appDbContent)
        {
            appDbContent = _appDbContent;
        }
        public IActionResult Index()
        {
            return View(appDbContent.Attributes.ToList());
        }



        public IActionResult Create()
        {
            ViewBag.Category = appDbContent.Categories.ToList();

            return View();
        }

        [HttpPost]
        public IActionResult Create(Models.Attribute model)
        {

            if (!ModelState.IsValid)
            {
                ViewBag.Category = appDbContent.Categories.ToList();
                return View(model);
            }

            appDbContent.Attributes.Add(model);
            appDbContent.SaveChanges();
            return RedirectToAction("Index");
        }




        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.Category = appDbContent.Categories.ToList();
            var model = appDbContent.Attributes.FirstOrDefault(x => x.Id == id);

            return View(model);
        }


        [HttpPost]
        public IActionResult Edit(Models.Attribute products)
        {
            ViewBag.Categories = appDbContent.Categories.ToList();
            if (!ModelState.IsValid)
            {
                return View(products);
            }

            appDbContent.Attributes.Update(products);
            appDbContent.SaveChanges();
            return RedirectToAction("Index");
        }


        //public IActionResult Edit(int id)
        //{
        //    if (id == 0)
        //    {
        //        return View("index");
        //    }
        //    var model = appDbContent.Products.FirstOrDefault(x => x.Id == id);
        //    if (model == null)
        //    {
        //        return RedirectToAction("Index");

        //    }
        //    return View(model);

        //}

        //[HttpPost]
        //public IActionResult Edit(Products products)
        //{

        //    if (!ModelState.IsValid)
        //    {
        //        return View(products);
        //    }
        //    appDbContent.Products.Update(products);
        //    appDbContent.SaveChanges();
        //    return RedirectToAction("Index");

        //}

        public JsonResult Delete(int id)
        {
            if (id == 0)
            {
                return Json(new
                {
                    status = 400
                });
            }

            var products = appDbContent.Attributes.Find(id); //axtarib tapiram
            if (products != null)
            {
                if (products.IsAvailable == true)
                {
                    products.IsAvailable = false;
                }
                else
                {
                    products.IsAvailable = true;
                }
                appDbContent.Attributes.Remove(products);
                appDbContent.SaveChanges();
            }

            return Json(new
            {
                status = 200
            });

        }







    }
}

emirathes/Areas/Admin/Views/Attributes/Create.cshtml
@model emirathes.Models.Attribute

<div class="page-content">
    <div class="container-fluid">

        <!-- start page title -->
        <div class="row">
            <div class="col-12">
            </div>
        </div>
        <!-- end page title -->
        <div class="row">
            <div class="col-lg-12">
                <div class="card job-filter">
                    <div class="card-body p-3">

                        <form class="row" method="post" asp-area="admin" asp-controller="attributes" asp-action="create" enctype="multipart/form-data">
                            @Html.AntiForgeryToken()
                            <div class="col-md-4">
                                <label>
                                    Title
                                </label>
                                <input asp-for="Title" type="text" class="form-control" />
                                <span asp-validation-for="Title" class="text-danger"></span>
                            </div>

                           
                            <div class="col-md-4">
                                <label>
                                    Baggage
                                </label>
                                <input asp-for="Baggage" type="text" class="form-control" />
                                <span asp-validation-for="Baggage" class="text-danger"></span>
                            </div>


                            <div class="col-md-4">
                                <label>
                                    Cabin Baggage
                                </label>
                                <input asp-for="CabinBaggage" type="text" class="form-control" />
                                <span asp-validation-for="CabinBaggage" class="text-danger"></span>
                            </div>
                            
                           @*  <div class="col-md-3">
                                <label>
                                    Category
                                </label>
                                <br />
                                <select class="form-select" asp-for="CategoryId" style="width:200px; height:38px">
                                    @foreach (var item in ViewBag.Category)
                                    {
                                        <option value="@item.Id">@item.TicketsClassName</option>

                                    }    
                                </select>
                            </div> *@

                         

                            <div class="col-md-3">
                                <button type="submit" class="btn btn-success mt-3 btn-block">Add database</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

        </div>

    </div>
</div><!-- End Page-cont

emirathes/Areas/Admin/Views/Attributes/Edit.cshtml
@model emirathes.Models.Attribute


<div class="page-content">
    <div class="container-fluid">



        <div class="row">
            <div class="col-lg-12">
                <div class="card job-filter">
                    <div class="card-body p-3">

                        <form class="row" method="post" asp-area="admin" asp-controller="attributes" asp-action="create" enctype="multipart/form-data">
                            @Html.AntiForgeryToken()
                            <div class="col-md-4">
                                <label>
                                    Title
                                </label>
                                <input asp-for="Title" type="text" class="form-control" />
                                <span asp-validation-for="Title" class="text-danger"></span>
                            </div>


                            <div class="col-md-4">
                                <label>
                                    Baggage
                                </label>
                                <input asp-for="Baggage" type="text" class="form-control" />
                                <span asp-validation-for="Baggage" class="text-danger"></span>
                            </div>


                            <div class="col-md-4">
                                <label>
                                    Cabin Baggage
                                </label>
                                <input asp-for="CabinBaggage" type="text" class="form-control" />
                                <span asp-validation-for="CabinBaggage" class="text-danger"></span>
                            </div>

                          @*   <div class="col-md-3">
                                <label>
                                    Category
                                </label>
                                <br />
                                <select class="form-select" asp-for="CategoryId" style="width:200px; height:38px">
                                    @foreach (var item in ViewBag.Category)
                                    {
                                        <option value="@item.Id">@item.TicketsClassName</option>

                                    }
                                </select>
                            </div> *@

                            <div class="col-md-4">
                                <label>
                                    Reviewed
                                </label>
                                <input asp-for="IsAvailable" type="checkbox" class="form-check" />
                            </div>


                           
                            <div class="col-md-4">
                                <button type="submit" class="btn btn-success mt-3 btn-block la la-pencil">Edit</button>
                            </div>

                        </form>
                    </div>
                </div>
            </div>

        </div>

    </div>
</div>

emirathes/Areas/Admin/Views/Attributes/Index.cshtml
@model             List<emirathes.Models.Attribute>

@section Styles {
    <link href="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/8.11.8/sweetalert2.min.css" rel="stylesheet" />

}



<div class="page-content">
    <div class="container-fluid">

        <a class="btn btn-success mt-2 mb-2" asp-area="Admin" asp-controller="Attributes" asp-action="Create">Create new Products</a>

        <div class="row">
            <div class="col-lg-12">
                <div class="card job-filter">
                    <div class="card-body p-3">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th scope="col"> Title</th>
                                    <th scope="col">Baggage</th>
                                    <th scope="col">CabinBaggage</th>
                                   @*  <th scope="col">Category</th> *@
                                    <th scope="col">Operation</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @item.Title
                                        </td>
                                        <td>
                                            @item.Baggage
                                        </td>
                                        <td>
                                            @item.CabinBaggage
                                        </td>

                                       @*  <td>
                                            @item.Category.TicketsClassName
                                        </td> *@

                                        <td>
                                            <a class="deleteBtn btn btn-danger" asp-area="Admin" asp-controller="Attributes" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                                            <a class="btn btn-success" asp-area="Admin" asp-controller="Attributes" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

        </div>

    </div>
</div><!-- End Page-content -->
@section Scripts {
    <script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/8.11.8/sweetalert2.min.js"></script>

    <script>

        $(document).ready(function () {
            $(document).on('click', '.deleteBtn', function (e) {
                e.preventDefault();
                let url = $(this).attr("href");
                let element = this.parentElement.parentElement;

                Swal.fire({
                    title: 'Are you sure want to delete this?',
                    text: "If you delete it, you can never get it back!",
                    type: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Delete',
                    cancelButtonText: 'Back'

                }).then((result) => {
                    if (result.value) {
                        $.ajax({
                            url: url,
                            type: "get",
                            dataType: "json",
                            success: function (response) {
                                console.log(response)
                                if (response.status == 200) {
                                    Swal.fire(
                                        'Deleted!',
                                        '',
                                        'success'
                                    )
                                    element.outerHTML = '';
                                }
                                else if (response.status == 400) {
                                    //toastr.error(response.message)
                                    Swal.fire({
                                        title: 'Error!',
                                        icon: 'error',
                                        confirmButtonText: 'Cool'
                                    })
                                }
                            }
                        });
                    }
                })
            });
        });
    </script>
}